Repository 2025-likelion-trenditon/KAvatar_Backend, pull requests merged in 2025-02, with the labels that each got.

#2 프로젝트 생성 및 기본 세팅
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/shop/kavatar/kavatarbackend/KAvatarBackendApplication.java
  src/main/java/shop/kavatar/kavatarbackend/global/config/JpaAuditingConfig.java
  src/main/java/shop/kavatar/kavatarbackend/global/config/QuerydslConfig.java
  src/main/java/shop/kavatar/kavatarbackend/global/config/RestClientConfig.java
  src/main/java/shop/kavatar/kavatarbackend/global/config/SwaggerConfig.java
  src/main/java/shop/kavatar/kavatarbackend/global/domain/BaseTimeEntity.java
  src/main/java/shop/kavatar/kavatarbackend/global/domain/Status.java
  src/main/java/shop/kavatar/kavatarbackend/global/error/dto/ErrorResponse.java
  src/main/java/shop/kavatar/kavatarbackend/global/error/exception/BadRequestException.java
  src/main/java/shop/kavatar/kavatarbackend/global/error/exception/ForbiddenException.java
  src/main/java/shop/kavatar/kavatarbackend/global/error/exception/GlobalExceptionHandler.java
  src/main/java/shop/kavatar/kavatarbackend/global/error/exception/NotFoundException.java
  src/main/java/shop/kavatar/kavatarbackend/global/error/exception/UnauthorizedException.java
  src/main/java/shop/kavatar/kavatarbackend/global/properties/SwaggerProperties.java
  src/main/java/shop/kavatar/kavatarbackend/global/template/ApiResponseTemplate.java
  src/main/resources/applicaion-test.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/shop/kavatar/kavatarbackend/KAvatarBackendApplicationTests.java
Labels: ⚙ Setting

#5 feat(#4): 배포 세팅
  Dockerfile
  build.gradle
  src/main/java/shop/kavatar/kavatarbackend/PingController.java
Labels: 🌏 Devops

#7 feat(#3): 회원 기능 구현
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberController.java
  src/main/java/shop/kavatar/kavatarbackend/member/application/MemberService.java
  src/main/java/shop/kavatar/kavatarbackend/member/domain/Member.java
  src/main/java/shop/kavatar/kavatarbackend/member/dto/request/CreateMemberRequest.java
  src/main/java/shop/kavatar/kavatarbackend/member/dto/response/MemberInfoResponse.java
  src/main/java/shop/kavatar/kavatarbackend/member/repository/MemberRepository.java
Labels: ✨ Feature

#10 옷 입히기 게임 기능 구현
  .github/workflows/deploy.yml
  src/main/java/shop/kavatar/kavatarbackend/dress/api/DressController.java
  src/main/java/shop/kavatar/kavatarbackend/dress/api/DressControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/dress/application/DressService.java
  src/main/java/shop/kavatar/kavatarbackend/dress/domain/Dress.java
  src/main/java/shop/kavatar/kavatarbackend/dress/dto/request/CreateDressRequest.java
  src/main/java/shop/kavatar/kavatarbackend/dress/dto/response/DressInfoResponse.java
  src/main/java/shop/kavatar/kavatarbackend/dress/dto/response/DressesInfoResponse.java
  src/main/java/shop/kavatar/kavatarbackend/dress/repository/DressRepository.java
  src/main/java/shop/kavatar/kavatarbackend/member/domain/Member.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#12 초성 게임 기능 구현
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/api/InitialConsonantController.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/api/InitialConsonantControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/application/InitialConsonantMember.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/application/InitialConsonantService.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/domain/AnswerStatus.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/domain/InitialConsonant.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/domain/InitialConsonantCategory.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/dto/request/InitialConsonantPlayRequest.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/dto/request/InitialConsonantResultRequest.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/dto/response/InitialConsonantResultResponse.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/dto/response/InitialConsonantResultsResponse.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantCustomRepository.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantCustomRepositoryImpl.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantMemberRepository.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantRepository.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberController.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/member/domain/Member.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#14 초성 게임 정답 맞추면 점수 부여
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/application/InitialConsonantService.java
Labels: ✨ Feature

#15 main push
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/api/InitialConsonantController.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/api/InitialConsonantControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/application/InitialConsonantMember.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/application/InitialConsonantService.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/domain/AnswerStatus.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/domain/InitialConsonant.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/domain/InitialConsonantCategory.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/dto/request/InitialConsonantPlayRequest.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/dto/request/InitialConsonantResultRequest.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/dto/response/InitialConsonantResultResponse.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/dto/response/InitialConsonantResultsResponse.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantCustomRepository.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantCustomRepositoryImpl.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantMemberRepository.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantRepository.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberController.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/member/domain/Member.java
  src/main/resources/application-local.yml
Labels: 🌏 Devops

#17 랭킹 조회 기능 구현
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/application/InitialConsonantService.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/domain/InitialConsonantMember.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantMemberRepository.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberController.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/member/application/MemberService.java
  src/main/java/shop/kavatar/kavatarbackend/member/domain/Member.java
  src/main/java/shop/kavatar/kavatarbackend/member/dto/response/MemberInfosResponse.java
  src/main/java/shop/kavatar/kavatarbackend/member/repository/MemberRepository.java
Labels: ✨ Feature

#18 main push
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/application/InitialConsonantService.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/domain/InitialConsonantMember.java
  src/main/java/shop/kavatar/kavatarbackend/initialconsonant/repository/InitialConsonantMemberRepository.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberController.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/member/application/MemberService.java
  src/main/java/shop/kavatar/kavatarbackend/member/domain/Member.java
  src/main/java/shop/kavatar/kavatarbackend/member/dto/response/MemberInfosResponse.java
  src/main/java/shop/kavatar/kavatarbackend/member/repository/MemberRepository.java
Labels: 🌏 Devops

#20 이미지 업현드 기능 구현
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  src/main/java/shop/kavatar/kavatarbackend/image/api/ImageController.java
  src/main/java/shop/kavatar/kavatarbackend/image/api/ImageControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/image/api/dto/response/ImageResDto.java
  src/main/java/shop/kavatar/kavatarbackend/image/application/ImageService.java
  src/main/java/shop/kavatar/kavatarbackend/image/domain/Image.java
  src/main/java/shop/kavatar/kavatarbackend/image/domain/repository/ImageRepository.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#23 옷 입히기 게임 변수 타입 수정
  src/main/java/shop/kavatar/kavatarbackend/dress/domain/Dress.java
  src/main/java/shop/kavatar/kavatarbackend/dress/dto/request/CreateDressRequest.java
  src/main/java/shop/kavatar/kavatarbackend/dress/dto/response/DressInfoResponse.java
Labels: 🔨 Refactor

#27 로그인 기능 구현
  build.gradle
  src/main/java/shop/kavatar/kavatarbackend/global/config/SecurityConfig.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberController.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/member/application/MemberService.java
  src/main/java/shop/kavatar/kavatarbackend/member/dto/request/LoginRequest.java
  src/main/java/shop/kavatar/kavatarbackend/member/repository/MemberRepository.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#28 main push
  build.gradle
  src/main/java/shop/kavatar/kavatarbackend/global/config/SecurityConfig.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberController.java
  src/main/java/shop/kavatar/kavatarbackend/member/api/MemberControllerDocs.java
  src/main/java/shop/kavatar/kavatarbackend/member/application/MemberService.java
  src/main/java/shop/kavatar/kavatarbackend/member/dto/request/LoginRequest.java
  src/main/java/shop/kavatar/kavatarbackend/member/repository/MemberRepository.java
  src/main/resources/application-local.yml
Labels: 🌏 Devops
